######################################################################
# Automatically generated by qmake (3.0) Wed May 4 06:25:29 2016
######################################################################

TEMPLATE = app
TARGET = tables
INCLUDEPATH += .

# Input
HEADERS += model.h
SOURCES += main.cpp

QT += quick

CONFIG -= app_bundle