######################################################################
# Automatically generated by qmake (3.0) tir. sep. 13 06:52:17 2016
######################################################################

QT+=qml
TEMPLATE = app
TARGET = qmlproperty
INCLUDEPATH += .

# Input
SOURCES += qmlproperty.cpp
CONFIG+=debug
