######################################################################
# Automatically generated by qmake (3.0) fre. aug. 19 11:39:40 2016
######################################################################

TEMPLATE = app
TARGET = connecttest
INCLUDEPATH += .
QT = core

# Input
SOURCES += connecttest.cpp


